### ISSUE TITLE
`bitblt` function cannot actually be called in `const`

### ISSUE THREAD

**Issue by RalfJung** [inflation/vapoursynth4-rs#3]
The [`bitblt` function](https://github.com/inflation/vapoursynth4-rs/blob/cd0c1892d8fdd23f349126b524bced5b6fcd8bfa/vapoursynth4-sys/src/helper.rs#L168) needs a mutable raw pointer (`dstp: *mut c_void`). There is currently no way to create such a pointer in `const` on stable. (Well, one can of course cast a shared reference to `*mut`, but then writing to that would be UB.)

The `copy_from_nonoverlapping` functions inside `bitblt`  were accidentally made stable on const, but can't actually be used. We are [debating](https://github.com/rust-lang/rust/pull/117905) whether we want to take back stabilization to avoid misuse (which we are already seeing).

Is there any issue with making `bitblt` not be `const fn` any more?

**Comment by inflation** [comment]
Not really. Thanks for letting me know.
